# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='wirebulletin.proto',
  package='ahimsa',
  serialized_pb='\n\x12wirebulletin.proto\x12\x06\x61himsa\"?\n\x0cWireBulletin\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\tB\x14\x42\x12WireBulletinProtos')




_WIREBULLETIN = descriptor.Descriptor(
  name='WireBulletin',
  full_name='ahimsa.WireBulletin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='ahimsa.WireBulletin.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='topic', full_name='ahimsa.WireBulletin.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='ahimsa.WireBulletin.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['WireBulletin'] = _WIREBULLETIN

class WireBulletin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WIREBULLETIN
  
  # @@protoc_insertion_point(class_scope:ahimsa.WireBulletin)

# @@protoc_insertion_point(module_scope)
